config/routes.rb
YoutubeOnRails::Application.routes.draw do

  resources :videos, only: [:index, :new, :create]
  root to: 'videos#index'
end

app/models/video.rb
class Video < ActiveRecord::Base
  attr_accessible :link
  YT_LINK_FORMAT = /\A.*(youtu.be\/|v\/|u\/\w\/|embed\/|watch\?v=|\&v=)([^#\&\?]*).*\Z/i
  validates :link, presence: true, format: YT_LINK_FORMAT

  before_create -> do
    uid = self.link.match(YT_LINK_FORMAT)
    self.uid = uid[2] if uid && uid[2]

    if self.uid.to_s.length != 11
      self.errors.add(:link, 'is invalid.')
      false
    elsif Video.where(uid: self.uid).any?
      self.errors.add(:link, 'is not unique.')
      false
    else
      get_additional_info
    end
  end

  private

  def get_additional_info
    begin
      client = YouTubeIt::OAuth2Client.new(dev_key: 'AIzaSyCAhs2Zz8eJ9rNOe4iHU5heTS2zv944SRs')
      video = client.video_by(uid)
      self.title = video.title
      self.duration = parse_duration(video.duration)
      self.author = video.author.name
      self.likes = video.rating.likes
      self.dislikes = video.rating.dislikes
    rescue
      self.title = '' ; self.duration = '00:00:00' ; self.author = '' ; self.likes = 0 ; self.dislikes = 0
    end
  end

  def parse_duration(d)
    hr = (d / 3600).floor
    min = ((d - (hr * 3600)) / 60).floor
    sec = (d - (hr * 3600) - (min * 60)).floor

    hr = '0' + hr.to_s if hr.to_i < 10
    min = '0' + min.to_s if min.to_i < 10
    sec = '0' + sec.to_s if sec.to_i < 10

    hr.to_s + ':' + min.to_s + ':' + sec.to_s
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController

  def index
    @videos = Video.order('created_at DESC')
  end
  def new
    @video = Video.new
  end

  def create
    @video = Video.new(params[:video])
    if @video.save
      flash[:success] = "Video added :)"
      redirect_to root_url
    else
      render 'new'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>YoutubeOnRails</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
  <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>" style="margin-top:10px">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= value %>
    </div>
  <% end %>
</div>

<%= yield %>

</body>
</html>

app/views/shared/_errors.html.haml
- if object.errors.any?
  .panel.panel-danger
    .panel-heading
      %h3.panel-title=" The following errors were found while submitting the form:"
    .panel-body
      %ul
        - object.errors.full_messages.each do |msg|
          %li=" msg"

app/views/videos/index.html.haml
.jumbotron.text-center{style:"margin:30px;border-radius:20px;"}
  .container
    %h1
      ="Share your videos with the world"
    %p
      ="Click the button below to share your video from YouTube."
    %p
      =link_to 'Add video now!', new_video_path, class: 'btn btn-primary btn-lg'

- if @videos.any?
  .container
    %h1 Latest videos
    #player-wrapper
    - @videos.in_groups_of(3) do |group|
      .row
        - group.each do |video|
          - if video
            .col-md-4
              .yt_video.thumbnail
                = image_tag "https://img.youtube.com/vi/#{video.uid}/mqdefault.jpg", alt: video.title, |
                  class: 'yt_preview img-rounded', :"data-uid" => video.uid                            |
                .caption
                  %h5= video.title
                  %p
                    Author:
                    %b= video.author
                  %p
                    Duration:
                    %b= video.duration
                  %p
                    %span.glyphicon.glyphicon.glyphicon-thumbs-up
                    = video.likes
                    %span.glyphicon.glyphicon.glyphicon-thumbs-down
                    = video.dislikes

app/views/videos/new.html.haml
%div.container
  %h1="New video"
  = form_for @video do |form|
    = render 'shared/errors', object: @video
    .form-group
      = form.label :link
      = form.text_field :link, class: 'form-control', require: true
      %span.help-block= "A link to the video on YouTube."
    = form.submit class: 'btn btn-primary'